# Generated by Django 4.2.1 on 2023-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrappping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anos', models.IntegerField()),
                ('obitos', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectos',
            name='author',
        ),
        migrations.DeleteModel(
            name='Cadeiras',
        ),
        migrations.DeleteModel(
            name='Projectos',
        ),
    ]
