# Generated by Django 4.2.1 on 2023-06-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_webscrappping_remove_projectos_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebScrappping',
            new_name='WebScrapping',
        ),
    ]
