# Generated by Django 4.2.1 on 2023-06-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('música', 'Música'), ('desporto', 'Desporto'), ('no_categorie', 'No Category')], default='no_categorie', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
